# Generated by Django 5.2 on 2025-05-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtable',
            old_name='image',
            new_name='ai_image',
        ),
        migrations.RenameField(
            model_name='showtable',
            old_name='name',
            new_name='phrase',
        ),
    ]
